### ISSUE TITLE
"/mf" をコマンドとして利用すると他プラグインとの干渉が起こる

### ISSUE THREAD

**Issue by Natu9** [Natu9/ModerationForm#2]

**Comment by Natu9** [comment]
https://twitter.com/rb_tatchan/status/1328732110031515648?s=19

**Comment by Natu9** [comment]
`/uf` を使うことにする

**Comment by Natu9** [comment]
@Natu9 

Todo
- `/uf` への変更

**Comment by Natu9** [comment]
```
commands:
 uf:
  description: ModerationFormを表示します。
  usage: "/uf"
  permission: moderationform.command.mf

permission: 
 moderationform.command.mf:
  default: op
  description: "OPのみ"
```

変更完了。
